// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Owner     int64              `json:"owner"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Token struct {
	Hash      []byte             `json:"hash"`
	UserID    int64              `json:"user_id"`
	Expiry    pgtype.Timestamptz `json:"expiry"`
	Scope     string             `json:"scope"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Password  []byte             `json:"password"`
	Activated bool               `json:"activated"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Version   int32              `json:"version"`
}

type UserPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int64 `json:"permission_id"`
}
