services:
  # API Database
  postgres-auth:
    image: postgres
    restart: always
    container_name: postgres-auth
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '4321:5432'

  # Tests Database
  postgres-tests:
    image: postgres
    restart: always
    container_name: postgres-tests
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    ports:
      - '4321:5432'

volumes:
  postgres:
